// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// bcdf
NumericVector bcdf(NumericMatrix data, NumericMatrix eval);
RcppExport SEXP _distdiffR_bcdf(SEXP dataSEXP, SEXP evalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type eval(evalSEXP);
    rcpp_result_gen = Rcpp::wrap(bcdf(data, eval));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_distdiffR_bcdf", (DL_FUNC) &_distdiffR_bcdf, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_distdiffR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
