# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Apply a toroidal shift to the pooled samples
#'
#' @param data A two column matrix of the pooled samples
#' @param n1 An integer sample size for the first sample
#' @param n2 An integer sample size for the second sample
#' @param propPnts A numeric proportion of points to be used as toroidal shift origins
#' @return A two column matrix of the shifted pooled samples
#' @export
ToroShiftData <- function(data, n1, n2, propPnts = 1) {
    .Call('_distdiffR_ToroShiftData', PACKAGE = 'distdiffR', data, n1, n2, propPnts)
}

#' Construct and compute bivariate cumulative distribution function values
#'
#' @param data A two column matrix for constructing the empirical bivariate cumulative distribution function (EBCDF)
#' @param eval A two column matrix for input into the EBCDF
#' @return A numeric vector of output values from the EBCDF
#' @export
bcdf <- function(data, eval) {
    .Call('_distdiffR_bcdf', PACKAGE = 'distdiffR', data, eval)
}

