# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Construct and compute bivariate cumulative distribution function values
#'
#' @param data A two column matrix for constructing the empirical bivariate cumulative distribution function (EBCDF)
#' @param eval A two column matrix for input into the EBCDF
#' @return A numeric vector of output values from the EBCDF
#' @export
bcdf <- function(data, eval) {
    .Call('_distdiffR_bcdf', PACKAGE = 'distdiffR', data, eval)
}

